### ISSUE TITLE
Database Generation Instructions

### ISSUE THREAD

**Issue by NickKramer87** [orchid-initiative/synthetic-database-project#57]
As a database creator, I want to be able to easily find instructions on how to download and run the program so I can use the program to create a synthetic discharge database using the input parameters of my choice.

Proposed Subtasks:
1. Write an instruction manual for the database creation tool that can be understood and used by a data analyst who is not familiar with the specific Synthea software.

Acceptance Criteria:
1. A written user manual that has been proofread by an outside data analyst.

**Comment by beckyphan** [comment]
@NickKramer87 FYI - Currently drafted Developer Guide is here: https://github.com/orchid-initiative/synthetic-database-project/blob/main/documentation/DEVELOPER_GUIDE.md

**Comment by TravisHaussler** [comment]
the studies are now defined as simple single argument commands.  We do need to expand our wiki instructions but that is a separate task
For now it is sufficient for a person to get started:
https://github.com/orchid-initiative/synthetic-database-project/wiki
