### ISSUE TITLE
Fix Incomplete HCAI Fields

### ISSUE THREAD

**Issue by NickKramer87** [orchid-initiative/synthetic-database-project#63]
As a data analyst, I need the synthetic database to contain all relevant fields so that I can ensure that the software that I will write to perform the analysis will work on the real-world data.

## Proposed Subtasks:
1. Identify all missing fields and determine which are necessary for analysis.
2. Add all additional necessary fields.
3. Create a separate Task for enumerating clearly the fabricated fields, truncated fields, and not-fully-mapped fields for later consideration during analysis.

## Acceptance Criteria:
1. A list of all relevant fields with checkmark boxes.  Those fields that are currently correctly outputted will have a checkmark.
2. Every item on the checklist is checked off.

### Remaining Critical fields with mistakes are:
- Procedure codes - #58
- Facility Identification Number - #84

### Remaining fully missing fields are:
- "external causes of morbidity" and POAs for them. 
_Not regularly used, we plan not to do_

- Type of Coverage and also Plan Code Number - #68 
_Appears to be fairly California specific and not really contemplated under the synthea claims data._

- Preferred Language Spoken - #94  

- Homelessness Indicator - #70

**Comment by TravisHaussler** [comment]
This is a bit open ended - sort of a catch-all project.  However, there are only a few remaining fully blank fields so lets leave this. 
Once we add the last few (like external causes of morbidity) we will create a new task to track the fields that need additional work or have important caveats for analysis.

**Comment by TravisHaussler** [comment]
Remaining fully missing fields are:

"external causes of morbidity" and POAs for them. (have not found yet)
Type of Coverage (not sure)
Plan Code Number (not sure)
Preferred Language Spoken (possible)
Homelessness Indicator (covered in a separate task)

**Comment by rileeki** [comment]
@TravisHaussler and @NickKramer87 -
Re: "external causes of morbidity", the analytics team does not regularly use these fields.  Also, Medicare's synthetic files leave these fields blank ([source](https://data.cms.gov/sites/default/files/2023-05/d51e1218-68c3-4c7c-9598-0b81f22fe903/User%20Guide%20-%20CMS%20Synthetic%20RIF%20Files%20May%202023_AM508_v2.pdf) pg 29).  I think we're good to leave these blank and consider that done.

**Comment by TravisHaussler** [comment]
Excellent!

**Comment by beckyphan** [comment]
Per thread above, remaining issues are resolved and/or captured in new issues.
