### ISSUE TITLE
Additional Output Formats

### ISSUE THREAD

**Issue by NickKramer87** [orchid-initiative/synthetic-database-project#75]
As a data analyst, I would like the synthetic patient generator to be able to output data in several relevent formats so that it can be immediately used with pre-existing software.

Suggested Subtasks:
1.  Identify additional output formats that might be desired.
2. Implement those formats.

Acceptance Criteria:
1.  The code can output in any of the formats identified in subtask 1.

**Comment by TravisHaussler** [comment]
@lisasnortheim,@masonium, and @TravisHaussler to discuss design.  @TravisHaussler to implement

**Comment by TravisHaussler** [comment]
A functional version of this is done

I will refine further with @masonium when we review together
