### ISSUE TITLE
Output Inpatient Records in HCAI PDD Format

### ISSUE THREAD

**Issue by rileeki** [orchid-initiative/synthetic-database-project#78]
**Context:**
As of this message in Oct 2023, we are trying to output data in the [HCAI inpatient data submission format](https://hcai.ca.gov/wp-content/uploads/2022/12/IP-format-and-file-specs-jan-2023.pdf) (ie, the format that California hospitals use to submit quarterly data to the state). For the LARC project, we'll need output in the [HCAI research data format](https://hcai.ca.gov/data-and-reports/request-data/data-documentation/) (ie, the format of the data that eligible researchers can [buy](https://hcai.ca.gov/data-and-reports/request-data/oshpd-data-pricing-policy/) from California). The LARC project will only need the PDD (patient discharge data) file from the HCAI research data format - that's still just inpatient data, not worrying about other claim types yet.

**Acceptance Criteria:**
- [ ] A sample dataset has been produced in .csv format, consistent with the specifications in the [HCAI Data Dictionary for Patient Discharge Data (PDD)](https://hcai.ca.gov/wp-content/uploads/2023/10/PDD_DataDictionary_2022_Final-ADA.pdf).

**Comment by TravisHaussler** [comment]
@lisasnortheim and @masonium to give overview guidance to @TravisHaussler and then check back in with him after some work

**Comment by TravisHaussler** [comment]
A functional version of this is complete.  It is notably missing:

- Additional Race statistics (can be coded, just havn't done yet)
- Facility Identification Number (#84)
- Diagnostic categories (HARD - add a new task) (Major Diagnostic Category and Medicare-Severity Diagnosis-Related groupings)

**Comment by TravisHaussler** [comment]
Example from the latest run:
[csv_HCAIPDD_12-14-2023_1416.csv](https://github.com/orchid-initiative/synthetic-database-project/files/13679383/csv_HCAIPDD_12-14-2023_1416.csv)
