### ISSUE TITLE
Custom mapping for LARC-related procedures

### ISSUE THREAD

**Issue by rileeki** [orchid-initiative/synthetic-database-project#90]
@TravisHaussler [Here's](https://docs.google.com/spreadsheets/d/1d1C-clON4Rpxo4NY9U6fN_mk-ygkZigVOyv3xOlAdBc/edit?usp=sharing) a document with the procedure codes related to LARC implantation.

**Comment by TravisHaussler** [comment]
Search the strings in synthea git hub too just to see!
