### ISSUE TITLE
Clinical Module Exploration

### ISSUE THREAD

**Issue by NickKramer87** [orchid-initiative/synthetic-database-project#93]
As an organization that will be working with the Synthea patient generator, it would be useful to be able to develop clinical modules to add to the Synthea patient probability workflow that better represent the issues we are analyzing.

Action Items:
1.  Riley will meet with Dr. Franks to discuss the possibility of adding a clinical module about LARC.  This will include a discussion of the existing research and how best to determine the probabilities of specific outcomes for specific (artificial) patients.
2. If this seems viable, then we will make a new task to meet with Kurtis in order to discuss the programming requirements of creating this module.

**Comment by rileeki** [comment]
Dr. Franks is on board.  We discussed a bunch of options, but to start with, let's try adding in LARC. 
 She gave me these specifications:

In the [pregnancy module](https://synthetichealth.github.io/module-builder/#pregnancy), after `Normal_Pregnancy_Completion`, if there was no pregnancy complication, place LARC with this probability distribution:

SNOMED Code | Probability | Description
-- | -- | --
65200003 | 8.236% | Insertion of intrauterine contraceptive device
169553002 | 3.364% | Insertion of subcutaneous contraceptive
blank | 88.4% | None

---
More details for the record:
This comes from a [2021 publication](https://www.researchgate.net/publication/355151254_Use_of_Immediate_Postpartum_Long-Acting_Reversible_Contraception_Before_and_After_a_State_Policy_Mandated_Inpatient_Access) that found that in a state with mandated inpatient access to LARC, it is done 11.6% of the time.  Of those, hormonal LNG (levonorgestrel) IUDs are 56.5%, copper IUDs are 14.5%, and nexplanon (subcutaneous implants) are 29.1%.  We translated this to say that of the 11.6% of patients where IPP LARC is placed, 71% are IUDs, and 29% are subcutaneous contraceptives.  


Brant AR, Kollikonda S, Yao M, Mei L, Emery J. Use of Immediate Postpartum Long-Acting Reversible Contraception Before and After a State Policy Mandated Inpatient Access. Obstet Gynecol. 2021 Nov 1;138(5):732-737. doi: 10.1097/AOG.0000000000004560. PMID: 34619694.

A couple other notes from Dr. Franks:
- The LARC stays in place for avg 4 years
- We should also include injectable contraceptives, which happen frequently during L&D stays.  26% get Depo after pregnancy, 62.6% of those are during the hospital stay.
- An easy, uncontroversial update would be to change the contraceptive maintenance periodic replacement numbers.  They’re out of date.
- In the Female_Reproduction module, change reproductive age
- Add in twinning rates & outcomes
- Account for the timing of initial visit in likelihood of complications
- Go past 41 weeks
- Big project: maternal deaths
